### ISSUE TITLE
Profile page for each fellow

### ISSUE THREAD

**Issue by marcnjaramillo** [MLH-Fellowship/prep-portfolio-22.JUL.PREP.2#9]
When you click on each fellows card, it sends you to a separate page which includes more detail such as:

- Description
- Favourite programming languages
- Interests outside of technology
- University

**Comment by jhashivam-2001** [comment]
@sumana2001 Hey , please assign this issue to Me, Tiffany and Abdul ! We have finished with our previous issue.
